# Basic Python

## 1. Split this string

In [5]:
s = "Hi there Sam!"

In [7]:
s1=s.split()
s1

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [8]:
planet = "Earth"
diameter = 12742

In [9]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [10]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [14]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [15]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [17]:
s=np.zeros(10)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
s1=np.array([5]*10)
s1

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [19]:
s2=np.arange(20,36,2)
s2

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
s3=np.arange(0,9).reshape(3,3)
s3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [24]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
s4=np.concatenate((a,b))
s4

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [25]:
import pandas as pd


In [30]:
s5=pd.DataFrame({'Name':['Happiness','W','Goblin'],'Year':[2021,2016,2016]})
s5

Name  Year
0  Happiness  2021
1          W  2016
2     Goblin  2016

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [31]:
s6=pd.date_range(start='1-1-2023',end='10-2-2023',freq='d')
s6

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [32]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [34]:
s7=pd.DataFrame.from_records(lists)
s7

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24